name: AI powered Test Framework co-pilot
on:
  workflow_dispatch:
    inputs:
      github_url:
        description: "Code repository URL"
        default: "https://github.com/2022mt93280/bits_dissertation"
        required: true

jobs:
  code_locator:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Located code repository"

  code_crawler:
    runs-on: [ubuntu-latest]
    needs: code_locator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Crawling code repository and finding java files"

  instrument_code:
    runs-on: [ubuntu-latest]
    needs: code_locator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Instrument code repository with code coverage tools"

  function_extractor:
    runs-on: [ubuntu-latest]
    needs: code_crawler
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Extracting functions from java files"

  test_generator:
    runs-on: [ubuntu-latest]
    needs: function_extractor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Generating test cases for extracted functions"

  test_assembler:
    runs-on: [ubuntu-latest]
    needs: test_generator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Assembling generated test cases into meaningful test suite"

  test_executor:
    runs-on: [ubuntu-latest]
    needs: [test_assembler, instrument_code]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Executing test suites on instrumented code"

  code_coverage_report:
    runs-on: [ubuntu-latest]
    needs: [test_executor]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo stage name
        run: echo "Prepare code coverage report to find how much code is covered by the tests"
